#ifndef VIEWS_STATES_ENUM_HPP
#define VIEWS_STATES_ENUM_HPP

namespace places {

enum ViewsStatesEnum {
    LOGIN,
    REGISTER_PERSON,
    REGISTER_COMPANY,
    COMPANY_INITIAL_PAGE,
    USER_INITIAL_PAGE,
    PLACE_DESCRIPTION,
    PLACE_REVIEWS,
    PLACE_EVENTS,
    PLACE_ADD,
    USER_FRIENDS_REQUESTS,
    USER_FRIENDS_LIST,
    EXIT
};
}

#endif
